version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: auth0
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data: